version: '3'
services:
    api-flask:
        container_name: api-flask
        build: ./flask
        # command: python -m flask run --host=0.0.0.0 --port=5000
        command: python3 app.py run --host=0.0.0.0 --port=5000
        ports:
            - 5000:5000
        environment:
            - FLASK_APP=app.py
        env_file:
            - ./flask/.env
        depends_on:
            - db-postgres
        networks:
            - htn_prj
        volumes:
            - ./flask/:/api
        
    db-postgres:
        container_name: db-postgres
        image: postgres
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=htn_db
        volumes:
            - flask_htn_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - htn_prj
      
    nginx-flask:
        container_name: nginx-flask
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            # - sock:/sock
        ports:
            - "80:80"
        networks:
            - htn_prj
      

volumes:
    flask_htn_data:
          name: db-flask-htn

networks:
  htn_prj:
    external: true